# Generated by Django 2.0.6 on 2018-06-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away_team', models.CharField(max_length=250)),
                ('home_team', models.CharField(max_length=250)),
                ('goal_home', models.IntegerField(blank=True)),
                ('goal_away', models.IntegerField(blank=True)),
            ],
        ),
    ]
